name = "keep-expense-manager-bot"
main = "bot_worker/worker.py"
compatibility_date = "2024-11-01"

compatibility_flags = [ "python_workers" ]

[vars]
# Add non-sensitive variables here if needed
# Sensitive variables should be set via `wrangler secret put`

[env.production]
# Production specific overrides

[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true

[[kv_namespaces]]
binding = "BOT_USERS_KV"
id = "0665d7944a85454480ff73eaa8cefe48"